name: CD Pipeline

on:
  workflow_dispatch:
    # types: [trigger-cd]
    inputs:
      description: 'region'
      required: true
      default: 'us-east-1'
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Add your deployment steps here
      - name: Deploy
        run: |
          # Add your deployment script or commands here
          echo "Deploying..."
